import json
from pathlib import Path

from .constants import EPNames, OlivePassNames, OlivePropertyNames
from .model_parameter import ModelParameter, OptimizationPath, RuntimeOverwrite
from .utils import open_ex


def create_model_parameter(aitk, name: str, configFile: Path):
    oliveFile = aitk.get("oliveFile")
    requirements = aitk.get("requirements", None)
    runtimeOverwrite = None
    if requirements:
        runtimeOverwrite = RuntimeOverwrite(autoGenerated=True, executeRequirement=requirements)
    aitkRuntimeOverwrite = aitk.get("runtimeOverwrite")
    if aitkRuntimeOverwrite:
        if runtimeOverwrite is None:
            runtimeOverwrite = RuntimeOverwrite(autoGenerated=True)
        executeEp = aitkRuntimeOverwrite.get("executeEp")
        runtimeOverwrite.executeEp = EPNames(executeEp)

    requirements_patches = aitk.get("requirementsPatches")
    evalRuntime = aitk.get("evalRuntime")
    epMinVersions = aitk.get("epMinVersions")

    parameter = ModelParameter(
        name=name,
        oliveFile=oliveFile,
        runtimeOverwrite=runtimeOverwrite,
        executeRuntimeFeatures=requirements_patches,
        evalRuntime=evalRuntime,
        optimizationPaths=[],
        isGPURequired=aitk.get("isGPURequired", None),
        isGPUSuggested=aitk.get("isGPUSuggested", None),
        epMinVersions={EPNames(k): v for k, v in epMinVersions.items()} if epMinVersions else None,
    )
    parameter._file = str(configFile) + ".config"
    return parameter


def add_optimization_wa(optimizationPaths: list[OptimizationPath], k: str, v: dict) -> bool:
    if OlivePropertyNames.Precision in v:
        optimizationPaths.append(
            OptimizationPath(
                name="WeightType",
                path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Precision}",
            )
        )
        # We require both weight and activation type for quantization
        optimizationPaths.append(
            OptimizationPath(
                name="ActivationType",
                path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.ActivationType}",
            )
        )
        return True
    return False


def set_optimization_path(parameter: ModelParameter, configFile: str):
    parameter.optimizationPaths = []
    with open_ex(configFile, "r") as f:
        content = json.load(f)
    for k, v in content[OlivePropertyNames.Passes].items():
        vType = v[OlivePropertyNames.Type].lower()
        if vType == OlivePassNames.OrtTransformersOptimization:
            float16 = v.get(OlivePropertyNames.Float16)
            if float16 is not None:
                parameter.optimizationPaths.append(
                    OptimizationPath(
                        name="fp16",
                        path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Float16}",
                    )
                )
                return
        elif vType == OlivePassNames.OpenVINOQuantization:
            # TODO it is not specified, default 8 bit https://docs.openvino.ai/2025/openvino-workflow/model-optimization-guide/quantizing-models-post-training/basic-quantization-flow.html#quantize-a-model
            parameter.optimizationPaths.append(
                OptimizationPath(
                    name="int8",
                    path=f"{OlivePropertyNames.Passes}.{k}",
                )
            )
            return
        elif vType in [
            OlivePassNames.OnnxQuantization,
            OlivePassNames.OnnxStaticQuantization,
            OlivePassNames.OnnxDynamicQuantization,
        ]:
            add_optimization_wa(parameter.optimizationPaths, k, v)
            return
        elif vType == OlivePassNames.OnnxFloatToFloat16:
            parameter.optimizationPaths.append(
                OptimizationPath(
                    name="fp16",
                    path=f"{OlivePropertyNames.Passes}.{k}",
                )
            )
            return
        elif vType == OlivePassNames.AitkPython:
            # Check AitkPython specific properties
            if k != OlivePassNames.AitkPython:
                raise Exception(f"AitkPython pass key must be '{OlivePassNames.AitkPython}' in {configFile}")
            if OlivePropertyNames.UserScript in v:
                parameter.aitkPython = v[OlivePropertyNames.UserScript]
                python_script = Path(configFile).parent / str(parameter.aitkPython)
                if not python_script.exists():
                    raise Exception(
                        f"UserScript file {python_script} does not exist for AitkPython pass in {configFile}"
                    )
            else:
                raise Exception(f"UserScript is required for AitkPython pass in {configFile}")
            wa_added = add_optimization_wa(parameter.optimizationPaths, k, v)
            if wa_added:
                return
            else:
                # TODO handle other optimization types if needed
                return

    # If no known optimization pass found, try to at least set the optimization path for OnnxConversion if present
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.OnnxConversion:
            path = f"{OlivePropertyNames.Passes}.{k}"
            parameter.optimizationPaths.append(OptimizationPath(path=path, name="fp32"))
            return
