import json
from pathlib import Path
from typing import Optional

from .constants import OlivePassNames, OlivePropertyNames, ParameterTypeEnum, PhaseTypeEnum
from .generator_common import create_model_parameter, set_optimization_path
from .model_info import ModelList
from .model_parameter import ModelParameter, OptimizationPath, Section
from .parameters import Parameter
from .utils import isLLM_by_id, open_ex


def generate_quantization_config(configFile: Path, parameter: ModelParameter) -> Optional[Section]:
    """
    Generates a quantization configuration section for the given file.
    """
    with open_ex(configFile, "r") as f:
        content = json.load(f)
    parameters = []
    optimize_path = None
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.ModelBuilder:
            path = f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Precision}"
            parameters.append(
                Parameter(
                    autoGenerated=True,
                    template=Parameter(
                        template="ModelBuilderPrecision",
                        path=path,
                    ),
                )
            )
            parameter.optimizationPaths.append(OptimizationPath(path=path))
            optimize_path = f"{OlivePropertyNames.Passes}.{k}"

    if parameters:
        return Section(
            autoGenerated=True,
            name="Optimization",
            phase=PhaseTypeEnum.Quantization,
            parameters=parameters,
            disableToggleGeneration=True,
            toggle=Parameter(
                autoGenerated=True,
                name="Optimize model",
                type=ParameterTypeEnum.Bool,
                path=optimize_path,
                readOnly=True,
                actions=[[], []],
            ),
        )
    return None


def generator_dml(id: str, recipe, folder: Path, modelList: ModelList):
    aitk = recipe.get("aitk", {})
    auto = aitk.get("auto", True)
    if not auto:
        return

    isLLM = isLLM_by_id(id)
    file = recipe.get("file")
    configFile = folder / file

    if not isLLM:
        modelParameter = ModelParameter.Read(str(configFile) + ".config")
        set_optimization_path(modelParameter, str(configFile))
        modelParameter.writeIfChanged()
        return

    name = "Convert to DirectML"

    parameter = create_model_parameter(aitk, name, configFile)
    parameter.isLLM = isLLM

    quantize = generate_quantization_config(configFile, parameter)
    if quantize:
        parameter.sections.append(quantize)

    parameter.writeIfChanged()
    print(f"\tGenerated DML configuration for {file}")
