"""
Model parameter configuration classes
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

import pydash
from deepdiff import DeepDiff
from model_lab import RuntimeEnum
from pydantic import BaseModel

from .base import BaseModelClass
from .constants import (
    EPNames,
    OliveDeviceTypes,
    OlivePassNames,
    OlivePropertyNames,
    ParameterActionTypeEnum,
    ParameterTagEnum,
    ParameterTypeEnum,
    PhaseTypeEnum,
)
from .model_info import ModelInfo, ModelList
from .parameters import Parameter, ParameterAction
from .utils import (
    GlobalVars,
    checkPath,
    get_eval_in_execute_runtime,
    get_eval_runtime,
    get_execute_runtime,
    get_target_system,
    isLLM_by_id,
    open_ex,
    printError,
    printProcess,
    printWarning,
)


class RuntimeOverwrite(BaseModel):
    # This tag is only used for the case that when we edit the json, we know the property is auto generated by sanitize.py so no need to care about it
    autoGenerated: Optional[bool] = None
    pyEnvPath: Optional[str] = None
    executeEp: Optional[EPNames] = None
    executeOliveDeviceType: Optional[OliveDeviceTypes] = None
    executeRequirement: Optional[str] = None
    # This is usually used for EP binary generation
    evaluateUsedInExecute: Optional[bool] = None

    def Check(self, oliveJson: Any):
        if self.executeEp and self.executeRequirement:
            printError(f"executeEp and executeRequirement should not both be set")
            return False
        if self.executeRequirement:
            pattern = r"^[^/\\]+/[^/\\]+_py\d\.\d+\.\d+$"
            if not re.match(pattern, self.executeRequirement):
                printError(f"executeRequirement should be like XXX/YYY_py3.13.6")
                return False
        if self.pyEnvPath:
            if not checkPath(self.pyEnvPath, oliveJson):
                return False
        return True


class Section(BaseModel):
    # This tag is only used for the case that when we edit the json, we know the property is auto generated by sanitize.py so no need to care about it
    autoGenerated: Optional[bool] = None
    name: str
    phase: PhaseTypeEnum
    description: Optional[str] = None
    parameters: List[Parameter]
    disableToggleGeneration: Optional[bool] = None
    toggle: Optional[Parameter] = None

    @staticmethod
    def datasetPathPattern(path: str):
        return re.fullmatch(r"data_configs\[(0|[1-9]\d{0,2})\]\.load_dataset_config\.data_name", path)

    def Check(
        self,
        templates: Dict[str, Parameter],
        _file: str,
        sectionId: int,
        oliveJson: Any,
        modelList: ModelList,
        emptyAllowed: bool,
    ):
        if not self.name:
            return False
        # if not self.description:
        #    return False
        # TODO add place holder for General?
        if not emptyAllowed and not self.parameters:
            printError(f"{_file} self.parameters is empty for {self.phase}.")

        for i, parameter in enumerate(self.parameters):
            if parameter.template:
                template = parameter.template
                if not isinstance(template, Parameter):
                    printError(f"{_file} section {sectionId} parameter {i} has wrong template")
                    continue
                if template.template not in templates:
                    printError(f"{_file} section {sectionId} parameter {i} has wrong template")
                    continue
                parameter.clearValue()
                parameter.applyTemplate(template)
                parameter.applyTemplate(templates[str(template.template)])
            if not parameter.Check(False, oliveJson, modelList):
                printError(f"{_file} section {sectionId} parameter {i} has error")

            # TODO move tag check into Parameter
            # TODO guess for possible tags
            if parameter.path and Section.datasetPathPattern(parameter.path):
                if self.phase == PhaseTypeEnum.Quantization:
                    if not parameter.tags or ParameterTagEnum.QuantizationDataset not in parameter.tags:
                        printError(f"{_file} section {sectionId} parameter {i} should have QuantizationDataset tag")
                elif self.phase == PhaseTypeEnum.Evaluation:
                    if not parameter.tags or ParameterTagEnum.EvaluationDataset not in parameter.tags:
                        printError(f"{_file} section {sectionId} parameter {i} should have EvaluationDataset tag")
            elif parameter.path and parameter.path.endswith("activation_type"):
                if not parameter.tags or ParameterTagEnum.ActivationType not in parameter.tags:
                    printError(f"{_file} section {sectionId} parameter {i} should have ActivationType tag")
            elif parameter.path and parameter.path.endswith("weight_type"):
                if not parameter.tags or ParameterTagEnum.WeightType not in parameter.tags:
                    printError(f"{_file} section {sectionId} parameter {i} should have WeightType tag")

        if self.toggle:
            if self.toggle.type != ParameterTypeEnum.Bool:
                printError(f"{_file} section {sectionId} toggle must use bool")
                return False
            if not self.toggle.Check(False, oliveJson, modelList):
                printError(f"{_file} section {sectionId} toggle has error")

        return True


class DebugInfo(BaseModel):
    autoGenerated: bool = True
    # This kind of config will
    # - could not disable quantization
    # - use modelbuilder for conversion
    # - output a model folder instead of model file
    useModelBuilder: Optional[str] = None
    # This kind of config will
    # - could not disable quantization
    # - use OpenVINOConversion for conversion
    useOpenVINOConversion: Optional[str] = None
    # This kind of config will
    # - could not disable quantization
    # - use OpenVINOConversion for conversion
    useOpenVINOOptimumConversion: Optional[str] = None
    # This kind of config will
    # - could not disable quantization
    # - use QuarkQuantization for conversion
    useQuarkQuantization: Optional[str] = None

    def setupUseX(self, oliveJson: Any):
        def getPass(passType: str):
            return next(
                (
                    k
                    for k, v in oliveJson[OlivePropertyNames.Passes].items()
                    if v[OlivePropertyNames.Type].lower() == passType
                ),
                None,
            )

        self.useModelBuilder = getPass(OlivePassNames.ModelBuilder)
        self.useOpenVINOConversion = getPass(OlivePassNames.OpenVINOConversion)
        self.useOpenVINOOptimumConversion = getPass(OlivePassNames.OpenVINOOptimumConversion)
        self.useQuarkQuantization = getPass(OlivePassNames.QuarkQuantization)

        notEmpty = [
            v
            for v in [
                self.useModelBuilder,
                self.useOpenVINOConversion,
                self.useOpenVINOOptimumConversion,
                self.useQuarkQuantization,
            ]
            if v
        ]
        self._use = notEmpty[0] if notEmpty else None
        if len(notEmpty) > 1:
            printError(f"should not mix them")
            return False
        return True

    def getUseX(self):
        return self._use

    def isEmpty(self):
        return not self._use


class OptimizationPath(BaseModel):
    path: str
    name: Optional[str] = None

    def Check(self, oliveJson: Any, toDisplayName: Dict[str, Dict[str, str]]) -> str | None:
        if not checkPath(self.path, oliveJson):
            return None

        value = pydash.get(oliveJson, self.path)
        # if we have name and name is in mapping, either use result in mapping or value
        if self.name and self.name in toDisplayName:
            if value not in toDisplayName[self.name]:
                printError(f"{self.path} value {value} not in known optimization names for {self.name}")
                return None
            return toDisplayName[self.name][value]
        # if we have name and name is not in mapping, treat value as boolean
        if self.name:
            return self.name if value else None
        # else use value directly
        return value


class ModelParameter(BaseModelClass):
    name: str
    oliveFile: Optional[str] = None
    # SET AUTOMATICALLY TO TRUE BY MODEL ID
    isLLM: Optional[bool] = None
    isIntel: Optional[bool] = None
    intelRuntimeValues: Optional[List[OliveDeviceTypes]] = None
    # For template using CUDA and no runtime overwrite, we need to set this so we know the target EP
    evalRuntime: Optional[RuntimeEnum] = None
    evalMetrics: Optional[Dict[str, str]] = None
    # when we only use random data for evaluation latency
    evalNoDataConfig: Optional[bool] = None
    debugInfo: Optional[DebugInfo] = None
    # TODO A SHORTCUT FOR PythonEnvironment + CUDA, should rename
    # This kind of config will
    # - setup runtimeOverwrite for CUDA EP and others
    #   + the previous EP is used for EPContextBinaryGeneator by PythonEnvironment
    isQNNLLM: Optional[bool] = None
    # SET AUTOMATICALLY TO TRUE WHEN CUDAExecutionProvider
    # When true, it means some passes need CUDA so user could not run it without
    isGPURequired: Optional[bool] = None
    # When true, it means some passes could benefit from GPU but could run without GPU
    isGPUSuggested: Optional[bool] = None
    # Free memory suggested to convert the model
    memoryGbSuggested: Optional[int] = None
    needHFLogin: Optional[bool] = None
    runtimeOverwrite: Optional[RuntimeOverwrite] = None
    executeRuntimeFeatures: Optional[List[str]] = None
    evaluationRuntimeFeatures: Optional[List[str]] = None
    pyEnvRuntimeFeatures: Optional[List[str]] = None
    # Default is False - CPU execution provider is only added when explicitly set to True
    addCpu: Optional[bool] = None
    epMinVersions: Optional[Dict[EPNames, str]] = None

    runtime: Optional[Parameter] = None
    runtimeInConversion: Optional[Parameter] = None
    optimizationPaths: Optional[List[OptimizationPath]] = None
    optimizationDefault: Optional[str] = None
    aitkPython: Optional[str] = None
    sections: List[Section] = []

    @staticmethod
    def Read(parameterFile: str):
        printProcess(parameterFile)
        with open_ex(parameterFile, "r") as file:
            parameterContent = file.read()
        modelParameter = ModelParameter.model_validate_json(parameterContent, strict=True)
        modelParameter._file = parameterFile
        modelParameter._fileContent = parameterContent
        return modelParameter

    def getIntelDevices(self) -> Iterator[OliveDeviceTypes]:
        for tmpDevice in OliveDeviceTypes:
            if tmpDevice == OliveDeviceTypes.Any:
                continue
            if self.intelRuntimeValues and tmpDevice not in self.intelRuntimeValues:
                continue
            yield tmpDevice

    def Check(self, templates: Dict[str, Parameter], oliveJson: Any, modelList: ModelList, modelInfo: ModelInfo):
        GlobalVars.configCheck.append(self._file)

        if not self.checkDebugInfo(oliveJson):
            return

        self.isLLM = isLLM_by_id(modelInfo.id) or None

        if self.sections and self.sections[0].phase == PhaseTypeEnum.Conversion:
            self.sections = self.sections[1:]
        self.sections.insert(
            0,
            Section(
                autoGenerated=True,
                name="Convert",
                phase=PhaseTypeEnum.Conversion,
                parameters=[],
            ),
        )

        # Add runtime
        syskey, system = get_target_system(oliveJson)
        currentEp: str = system[OlivePropertyNames.Accelerators][0][OlivePropertyNames.ExecutionProviders][0]
        self.runtime = self.createRuntime(syskey, system, currentEp)
        if not self.runtime.Check(False, oliveJson, modelList):
            printError(f"{self._file} runtime has error")

        # Add runtime overwrite
        if self.isQNNLLM:
            if not system[OlivePropertyNames.Type] == "PythonEnvironment":
                printError(f"{self._file}'s olive json does not use PythonEnvironment")
            self.runtimeOverwrite = RuntimeOverwrite(
                autoGenerated=True,
                pyEnvPath=f"{OlivePropertyNames.Systems}.{syskey}.{OlivePropertyNames.PythonEnvironmentPath}",
                executeEp=EPNames.CUDAExecutionProvider,
                evaluateUsedInExecute=True,
            )

        if self.runtimeOverwrite and not self.runtimeOverwrite.Check(oliveJson):
            printError(f"{self._file} runtime overwrite has error")

        for tmpDevice, section in enumerate(self.sections):
            # Add conversion toggle
            if section.phase == PhaseTypeEnum.Conversion:
                if not section.disableToggleGeneration:
                    conversion = None
                    if self.debugInfo:
                        conversion = self.debugInfo.getUseX()
                    if not conversion:
                        conversion = [
                            k
                            for k, v in oliveJson[OlivePropertyNames.Passes].items()
                            if v[OlivePropertyNames.Type].lower()
                            in [OlivePassNames.OnnxConversion, OlivePassNames.AitkPython]
                        ][0]
                    conversionPath = f"{OlivePropertyNames.Passes}.{conversion}"
                    section.toggle = Parameter(
                        autoGenerated=True,
                        name="Convert to ONNX format",
                        type=ParameterTypeEnum.Bool,
                        path=conversionPath,
                        actions=[[], []],
                        readOnly=True,
                    )

            # Add quantization toggle
            elif section.phase == PhaseTypeEnum.Quantization:
                if not section.disableToggleGeneration:
                    toggleReadOnly = None
                    actions = []
                    quantize = None
                    if self.debugInfo:
                        quantize = self.debugInfo.getUseX()
                    if quantize:
                        toggleReadOnly = True
                    else:
                        quantize = [
                            k
                            for k, v in oliveJson[OlivePropertyNames.Passes].items()
                            if v[OlivePropertyNames.Type].lower()
                            in [
                                OlivePassNames.OnnxQuantization,
                                OlivePassNames.OnnxStaticQuantization,
                                OlivePassNames.OnnxDynamicQuantization,
                                # for trtrtx
                                OlivePassNames.OnnxFloatToFloat16,
                            ]
                        ][0]
                        conversion = [
                            (k, v)
                            for k, v in oliveJson[OlivePropertyNames.Passes].items()
                            if v[OlivePropertyNames.Type].lower() == OlivePassNames.OnnxConversion
                        ][0]
                        actions = [
                            ParameterAction(
                                path=f"{OlivePropertyNames.Passes}",
                                type=ParameterActionTypeEnum.Update,
                                value={conversion[0]: conversion[1]},
                            )
                        ]
                    quantizePath = f"{OlivePropertyNames.Passes}.{quantize}"
                    section.toggle = Parameter(
                        autoGenerated=True,
                        name="Quantize model",
                        type=ParameterTypeEnum.Bool,
                        path=quantizePath,
                        readOnly=toggleReadOnly,
                        actions=[[], actions],
                    )

            # Add evaluation toggle
            elif section.phase == PhaseTypeEnum.Evaluation:
                if not section.disableToggleGeneration:
                    action = ParameterAction(
                        path=OlivePropertyNames.Evaluator,
                        type=ParameterActionTypeEnum.Delete,
                    )
                    section.toggle = Parameter(
                        autoGenerated=True,
                        name="Evaluate model performance",
                        type=ParameterTypeEnum.Bool,
                        path=OlivePropertyNames.Evaluator,
                        actions=[[], [action]],
                    )
                evaluatorName = oliveJson[OlivePropertyNames.Evaluator]
                if not checkPath(f"{OlivePropertyNames.Evaluators}.{evaluatorName}", oliveJson):
                    printError(f"{self._file} does not have evaluator {evaluatorName}")

            emptyAllowed = (section.phase == PhaseTypeEnum.Conversion) or (
                section.phase == PhaseTypeEnum.Evaluation and self.evalNoDataConfig is True
            )
            if not section.Check(templates, self._file or "", tmpDevice, oliveJson, modelList, emptyAllowed):
                printError(f"{self._file} section {tmpDevice} has error")

        if currentEp == EPNames.CUDAExecutionProvider.value or (
            self.runtimeOverwrite and self.runtimeOverwrite.executeEp == EPNames.CUDAExecutionProvider
        ):
            self.isGPURequired = True

        # model builder uses AutoConfig.from_pretrained(hf_name, token=hf_token, trust_remote_code=True, **extra_kwargs) and trust_remote_code=True requires token
        first_pass_value = next(iter(oliveJson[OlivePropertyNames.Passes].values()), None)
        if first_pass_value and first_pass_value[OlivePropertyNames.Type].lower() == OlivePassNames.ModelBuilder:
            self.needHFLogin = True

        if self.evalMetrics and len(self.evalMetrics) > 3:
            printError(f"{self._file} evalMetrics should not have more than 3 metrics")

        self.checkPhase(oliveJson, self.evalNoDataConfig or False)
        self.CheckRuntimeInConversion(oliveJson, modelList, modelInfo)
        self.checkOliveFile(oliveJson, modelInfo)
        self.checkRequirements(modelList)
        self.checkOptimizationPaths(modelList.OptimizationToDisplayName, oliveJson, modelInfo)
        if self.debugInfo and self.debugInfo.isEmpty():
            self.debugInfo = None
        self.writeIfChanged()

    def createRuntime(self, syskey: str, system: Dict[str, Any], currentEp: str):
        # Get currentRuntimeRPC
        currentOliveDeviceType = system[OlivePropertyNames.Accelerators][0].get(
            OlivePropertyNames.Device, OliveDeviceTypes.Any.value
        )

        if currentEp == EPNames.QNNExecutionProvider.value and currentOliveDeviceType == OliveDeviceTypes.Any.value:
            currentOliveDeviceType = OliveDeviceTypes.NPU.value

        currentRuntimeRPC = GlobalVars.GetRuntimeRPC(currentEp, currentOliveDeviceType)

        runtimeValues: List[str] = []
        runtimeDisplayNames = []
        runtimePath: str = ""
        runtimeActions = None

        if currentEp == EPNames.OpenVINOExecutionProvider.value:
            runtimePath = (
                f"{OlivePropertyNames.Systems}.{syskey}.{OlivePropertyNames.Accelerators}.0.{OlivePropertyNames.Device}"
            )
            for tmpDevice in self.getIntelDevices():
                tmpRuntimeRPC = GlobalVars.GetRuntimeRPC(EPNames.OpenVINOExecutionProvider, tmpDevice)
                runtimeValues.append(GlobalVars.RuntimeToOliveDeviceType[tmpRuntimeRPC].value)
                runtimeDisplayNames.append(GlobalVars.RuntimeToDisplayName[tmpRuntimeRPC])
        else:
            runtimePath = f"{OlivePropertyNames.Systems}.{syskey}.{OlivePropertyNames.Accelerators}.0.{OlivePropertyNames.ExecutionProviders}.0"
            runtimeList = [currentRuntimeRPC]
            # CPU always last
            if self.addCpu and currentRuntimeRPC != RuntimeEnum.CPU:
                runtimeList.append(RuntimeEnum.CPU)
            if len(runtimeList) > 1:
                runtimeActions = []

            def addEP(runtimeEnum: RuntimeEnum):
                runtimeValues.append(GlobalVars.RuntimeToEPName[runtimeEnum].value)
                runtimeDisplayNames.append(GlobalVars.RuntimeToDisplayName[runtimeEnum])
                if runtimeActions is not None:
                    runtimeActions.append(
                        [
                            ParameterAction(
                                type=ParameterActionTypeEnum.Update,
                                path=runtimePath,
                                value=GlobalVars.RuntimeToEPName[runtimeEnum].value,
                            ),
                            ParameterAction(
                                type=ParameterActionTypeEnum.Update,
                                path=f"{OlivePropertyNames.Systems}.{syskey}.{OlivePropertyNames.Accelerators}.0.{OlivePropertyNames.Device}",
                                value=GlobalVars.RuntimeToOliveDeviceType[runtimeEnum].value,
                            ),
                        ]
                    )

            for runtime in runtimeList:
                addEP(runtime)

        self.runtime = Parameter(
            autoGenerated=True,
            name="Evaluate on",
            type=ParameterTypeEnum.Enum,
            values=runtimeValues,
            displayNames=runtimeDisplayNames,
            path=runtimePath,
            actions=runtimeActions,
            readOnly=False,
        )
        return self.runtime

    def CheckRuntimeInConversion(self, oliveJson: Any, modelList: ModelList, modelInfo: ModelInfo):
        self.runtimeInConversion = None
        return

        def getOpenVINOPass(passType: str):
            return next(
                (
                    (k, v)
                    for k, v in oliveJson[OlivePropertyNames.Passes].items()
                    if v[OlivePropertyNames.Type].lower() == passType
                ),
                None,
            )

        openVINOOptimumConversion = getOpenVINOPass(OlivePassNames.OpenVINOOptimumConversion)
        openVINOQuantization = getOpenVINOPass(OlivePassNames.OpenVINOQuantization)
        openVINOEncapsulation = getOpenVINOPass(OlivePassNames.OpenVINOEncapsulation)

        def addRuntimeInConversion(runtime: Parameter, path: str, values: List[Any]):
            if not runtime.path:
                runtime.path = path
                runtime.values = values
                runtime.displayNames = [
                    GlobalVars.RuntimeToDisplayName[GlobalVars.GetRuntimeRPC(EPNames.OpenVINOExecutionProvider, e)]
                    for e in values
                ]
            else:
                if runtime.actions is None:
                    runtime.actions = []
                for i in range(len(values)):
                    if i >= len(runtime.actions):
                        runtime.actions.append([])
                    runtime.actions[i].append(
                        ParameterAction(
                            path=path,
                            type=ParameterActionTypeEnum.Update,
                            value=values[i],
                        )
                    )

        if openVINOOptimumConversion or openVINOQuantization or openVINOEncapsulation:
            self.runtimeInConversion = Parameter(
                autoGenerated=True, name="Convert/Quantize to", type=ParameterTypeEnum.Enum
            )
            if openVINOOptimumConversion:
                addRuntimeInConversion(
                    self.runtimeInConversion,
                    f"{OlivePropertyNames.Passes}.{openVINOOptimumConversion[0]}.{OlivePropertyNames.ExtraArgs}.{OlivePropertyNames.Device}",
                    # TODO support any after olive release
                    [e.value for e in self.getIntelDevices()],
                )
            if openVINOQuantization:
                addRuntimeInConversion(
                    self.runtimeInConversion,
                    f"{OlivePropertyNames.Passes}.{openVINOQuantization[0]}.{OlivePropertyNames.TargetDevice}",
                    # TODO support any after olive release
                    [e.value for e in self.getIntelDevices()],
                )
            if openVINOEncapsulation:
                addRuntimeInConversion(
                    self.runtimeInConversion,
                    f"{OlivePropertyNames.Passes}.{openVINOEncapsulation[0]}.{OlivePropertyNames.TargetDevice}",
                    # TODO support any after olive release
                    [e.value for e in self.getIntelDevices()],
                )
            if not self.runtimeInConversion.Check(False, oliveJson, modelList):
                printError(f"{self._file} runtime in conversion has error")

    def checkPhase(self, oliveJson: Any, evalNoDataConfig: bool):
        allPhases = [section.phase for section in self.sections]
        if len(allPhases) == 1 and allPhases[0] == PhaseTypeEnum.Conversion:
            pass
        elif (
            len(allPhases) == 2
            and allPhases[0] == PhaseTypeEnum.Conversion
            and allPhases[1] in [PhaseTypeEnum.Quantization, PhaseTypeEnum.Evaluation]
        ):
            pass
        elif (
            len(allPhases) == 3
            and allPhases[0] == PhaseTypeEnum.Conversion
            and allPhases[1] == PhaseTypeEnum.Quantization
            and allPhases[2] == PhaseTypeEnum.Evaluation
        ):
            pass
        else:
            printError(f"{self._file} has wrong phases {allPhases}")

        if (
            PhaseTypeEnum.Evaluation in allPhases
            and PhaseTypeEnum.Quantization in allPhases
            and not evalNoDataConfig
            and (OlivePropertyNames.DataConfigs not in oliveJson or len(oliveJson[OlivePropertyNames.DataConfigs]) != 2)
        ):
            printError(f"{self._file}'s olive json should have two data configs for evaluation")

    def checkOliveFile(self, oliveJson: Any, modelInfo: ModelInfo):
        if modelInfo.extension:
            return
        if modelInfo.template:
            return
        if self.aitkPython:
            return
        if not self.oliveFile:
            if (
                self.runtime
                and self.runtime.displayNames
                and self.runtime.displayNames[0]
                in [
                    GlobalVars.RuntimeToDisplayName[RuntimeEnum.DML],
                    # TODO this warning it is useless now
                    GlobalVars.RuntimeToDisplayName[RuntimeEnum.AMDGPU],
                    GlobalVars.RuntimeToDisplayName[RuntimeEnum.IntelCPU],
                    GlobalVars.RuntimeToDisplayName[RuntimeEnum.IntelGPU],
                    GlobalVars.RuntimeToDisplayName[RuntimeEnum.IntelNPU],
                ]
            ):
                return
            printWarning(f"{self._file} does not have oliveFile")
            return
        if self.oliveFile.startswith("o:"):
            if GlobalVars.olivePath:
                oliveFile = Path(GlobalVars.olivePath) / "examples" / self.oliveFile[2:]
            else:
                return
        elif self._file:
            # relative to aitk folder
            oliveFile = Path(self._file).parent.parent / self.oliveFile
            if not oliveFile.exists():
                printError(f"{self._file}'s oliveFile {self.oliveFile} does not exist")
                return
        else:
            raise Exception("Internal error: _file is not set")
        with open_ex(oliveFile, "r") as file:
            oliveFileJson = json.load(file)

        diff = DeepDiff(
            oliveFileJson[OlivePropertyNames.Passes],
            oliveJson[OlivePropertyNames.Passes],
        )

        addeds: list[str] = diff.pop("dictionary_item_added", [])
        newAddeds = []
        for added in addeds:
            if added.endswith("['save_as_external_data']"):
                # We add it to align model format
                pass
            else:
                newAddeds.append(added)
        if newAddeds:
            diff["dictionary_item_added"] = newAddeds

        removeds: list[str] = diff.pop("dictionary_item_removed", [])
        newRemoveds = []
        for removed in removeds:
            if removed == "root['add_metadata']":
                pass
            else:
                newRemoveds.append(removed)
        if newRemoveds:
            diff["dictionary_item_removed"] = newRemoveds

        changeds: dict[str, Any] = diff.pop("values_changed", {})
        newChangeds = {}
        for changed in changeds:
            if changed.endswith("['data_config']") or changed.endswith("['user_script']") or changed.endswith("['save_as_external_data']"):
                # Data config name or *.py could be different
                pass
            else:
                newChangeds[changed] = changeds[changed]
        if newChangeds:
            diff["values_changed"] = newChangeds

        if diff:
            path = Path(self._file if self._file else "UNKNOWN")
            printWarning(f"{"/".join(path.parts[-3:])} different from {self.oliveFile}\r\n{diff}")
        GlobalVars.oliveCheck += 1

    def checkDebugInfo(self, oliveJson: Any):
        self.debugInfo = DebugInfo()
        if not self.debugInfo.setupUseX(oliveJson):
            return False
        return True

    def checkRequirements(self, modelList: ModelList):
        if not self.runtime or not self.runtime.displayNames:
            printError(f"{self._file} runtime is not set")
            return

        req_path = Path(__file__).parent.parent.parent / "requirements"
        # TODO only check 1st one
        execute_runtime = modelList.DisplayNameToRuntimeRPC[self.runtime.displayNames[0]]
        if self.runtimeOverwrite and self.runtimeOverwrite.executeEp:
            execute_runtime = GlobalVars.GetRuntimeRPC(self.runtimeOverwrite.executeEp, OliveDeviceTypes.Any)
        if self.runtimeOverwrite and self.runtimeOverwrite.executeRequirement:
            execute_runtime_value = self.runtimeOverwrite.executeRequirement
        else:
            execute_runtime_value = get_execute_runtime(execute_runtime).value
        self.checkRequirement(req_path, execute_runtime_value)
        if self.executeRuntimeFeatures:
            for feature in self.executeRuntimeFeatures:
                self.checkRequirement(req_path, f"{execute_runtime_value}-{feature}")

        eval_runtime = modelList.DisplayNameToRuntimeRPC[self.runtime.displayNames[0]]
        if self.evalRuntime:
            eval_runtime = self.evalRuntime

        if self.runtimeOverwrite and self.runtimeOverwrite.evaluateUsedInExecute:
            eval_in_execute_runtime = get_eval_in_execute_runtime(eval_runtime)
            self.checkRequirement(req_path, eval_in_execute_runtime.value)
            if self.pyEnvRuntimeFeatures:
                for feature in self.pyEnvRuntimeFeatures:
                    self.checkRequirement(req_path, f"{eval_in_execute_runtime.value}-{feature}")

        eval_runtime = get_eval_runtime(eval_runtime, self.isLLM or False)
        self.checkRequirement(req_path, eval_runtime.value)
        if self.evaluationRuntimeFeatures:
            for feature in self.evaluationRuntimeFeatures:
                self.checkRequirement(req_path, f"{eval_runtime.value}-{feature}")

    def checkOptimizationPaths(self, toDisplayName: Dict[str, Dict[str, str]], oliveJson: Any, modelInfo: ModelInfo):
        if modelInfo.template or modelInfo.extension:
            return
        if not self.optimizationPaths:
            printError(f"{self._file} optimizationPaths is not set")
            return
        optimizationDefault = ""
        for optimizationPath in self.optimizationPaths:
            displayName = optimizationPath.Check(oliveJson, toDisplayName)
            if displayName:
                optimizationDefault += displayName
            else:
                printError(f"{self._file} optimization path {optimizationPath.path} has error")
                return
        if optimizationDefault:
            self.optimizationDefault = optimizationDefault
        else:
            printError(f"{self._file} optimizationDefault is not set")

    def checkRequirement(self, path: Path, name: str):
        file = path / f"{name}.txt" if "_py" in name else path / f"requirements-{name}.txt"
        if not file.exists():
            printError(f"Missing requirement file: {file} for {self._file}")
        else:
            GlobalVars.venvRequirementsCheck.add(str(file))
